const folder = "tabuas25";

export const arrLocations = [
  {name:"ARQUIPELAGO DE FERNANDO DE NORONHA", url:`${folder}/arquipelago_de_fernando_de_noronha.pdf`},
  {name:"ATRACADOURO DE BREVES", url:`${folder}/atracadouro_de_breves.pdf`},
  {name:"BARRA DE PARANAGUÁ - CANAL DA GALHETA", url:`${folder}/barra_de_paranagua_canal_da_galheta.pdf`},
  {name:"BARRA DE PARANAGUÁ - CANAL SUESTE", url:`${folder}/barra_de_paranagua_canal_sueste.pdf`},
  {name:"BARRA NORTE", url:`${folder}/barra_norte.pdf`},
  {name:"FUNDEADOURO DE SALINÓPOLIS", url:`${folder}/fund_de_salinopolis.pdf`},
  {name:"FUNDEADOURO DA ESTAÇÃO ANTÁRTICA COMANDANTE FERRAZ", url:`${folder}/fund_estacao_comandante_ferraz.pdf`},
  {name:"IGARAPÉ GRANDE DO CURUÁ", url:`${folder}/igarape_grande_do_curua.pdf`},
  {name:"ILHA DA TRINDADE", url:`${folder}/ilha_da_trindade.pdf`},
  {name:"ILHA DO MOSQUEIRO", url:`${folder}/ilha_do_mosqueiro.pdf`},
  {name:"ILHA DOS GUARÁS", url:`${folder}/ilha_dos_guaras.pdf`},
  {name:"PORTO DE ARATU", url:`${folder}/porto_de_aratu_base_naval.pdf`},
  {name:"PORTO DE AREIA BRANCA", url:`${folder}/porto_de_areia_branca.pdf`},
  {name:"PORTO DE BELEM", url:`${folder}/porto_de_belem.pdf`},
  {name:"PORTO DE GUARAME", url:`${folder}/porto_de_guamare.pdf`},
  {name:"PORTO DE IMBITUBA", url:`${folder}/porto_de_imbituba.pdf`},
  {name:"PORTO DE ITAGUAI", url:`${folder}/porto_de_itaguai.pdf`},
  {name:"PORTO DE ITAQUI", url:`${folder}/porto_de_itaqui.pdf`},
  {name:"PORTO DE ITAGUAÍ", url:`${folder}/itaguai.pdf`},
  {name:"PORTO DE LUIS CORREIA", url:`${folder}/porto_de_luis_correia.pdf`},
  {name:"PORTO DE MACAU", url:`${folder}/porto_de_macau.pdf`},
  {name:"PORTO DE MACEIÓ", url:`${folder}/porto_de_maceio.pdf`},
  {name:"PORTO DE MADRE DE DEUS", url:`${folder}/porto_madre_de_deus.pdf`},
  {name:"PORTO DE NATAL-CAPITANIA DOS PORTOS DO RN", url:`${folder}/porto_de_natal_capitania_dos_portos_do_rn.pdf`},
  {name:"PORTO DE MUCURIPE", url:`${folder}/porto_de_mucuripe.pdf`},
  {name:"PORTO DE PARANAGUÁ", url:`${folder}/porto_de_paranagua.pdf`},
  {name:"PORTO DE SANTANA - CIA DOCAS DE SANTANA", url:`${folder}/santana.pdf`},
  {name:"PORTO DE SÃO FRANCISCO DO SUL", url:`${folder}/porto_de_sao_francisco_do_sul.pdf`},
  {name:"PORTO DE SUAPE", url:`${folder}/porto_de_suape.pdf`},
  {name:"PORTO DE TUBARÃO", url:`${folder}/porto_de_tubarao.pdf`},
  {name:"PORTO DE TUTOIA", url:`${folder}/porto_de_tutoia.pdf`},
  {name:"PORTO DE VILA DO CONDE", url:`${folder}/porto_de_vila_do_conde.pdf`},
  {name:"PORTO DE VITÓRIA", url:`${folder}/porto_de_vitoria.pdf`},
  {name:"PORTO DO AÇU", url:`${folder}/porto_do_acu.pdf`},
  {name:"PORTO DO FORNO", url:`${folder}/porto_do_forno.pdf`},
  {name:"PORTO DO RECIFE", url:`${folder}/porto_do_recife.pdf`},
  {name:"PORTO DO RIO GRANDE", url:`${folder}/porto_do_rio_grande.pdf`},
  {name:"PORTO DO RIO DE JANEIRO - ILHA FISCAL", url:`${folder}/porto_do_rj_ilha_fiscal.pdf`},
  {name:"SÃO LUÍS - MARANHÃO", url:`${folder}/sao_luis.pdf`},
  {name:"TERMINAL ILHA GUAIBA", url:`${folder}/terminal_ilha_guaiba.pdf`},
  {name:"TERMINAL MARÍTIMO DE IMBETIBA", url:`${folder}/terminal_maritimo_de_imbetiba.pdf`},
  {name:"TERMINAL PORTUÁRIO DA PONTA DO FÉLIX", url:`${folder}/term_port_da_ponta_do_felix.pdf`},
  {name:"TERMINAL DA ALUMAR", url:`${folder}/terminal_da_alumar.pdf`},
  {name:"TERMINAL DA PONTA DA MADEIRA", url:`${folder}/terminal_da_ponta_da_madeira.pdf`},
  {name:"TERMINAL PONTA DO UBU", url:`${folder}/terminal_ponta_do_ubu.pdf`},
  {name:"TERMINAL DE BARRA DO RIACHO", url:`${folder}/terminal_de_barra_do_riacho.pdf`},
  {name:"TERMINAL PORTUÁRIO DO PECEM", url:`${folder}/terminal_do_portuario_do_pecem.pdf`}
];
